// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDh6jYuuuOVkMYW8ZzO-Xc_wg5G5KHnres',
//     appId: '1:882228347283:web:ac7c07d776b22e6a3d2866',
//     messagingSenderId: '882228347283',
//     projectId: 'easy-test-flutter-project-v1',
//     authDomain: 'easy-test-flutter-project-v1.firebaseapp.com',
//     storageBucket: 'easy-test-flutter-project-v1.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDgUbywmxNxS-aEgthVJXEFiiCcpXH4b_0',
//     appId: '1:882228347283:android:fc00cbbd1d1ab5b33d2866',
//     messagingSenderId: '882228347283',
//     projectId: 'easy-test-flutter-project-v1',
//     storageBucket: 'easy-test-flutter-project-v1.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDeR35Ypl3Q0YFsEiRDwsfP1vmWP2RhKok',
//     appId: '1:882228347283:ios:b4a089418879e05f3d2866',
//     messagingSenderId: '882228347283',
//     projectId: 'easy-test-flutter-project-v1',
//     storageBucket: 'easy-test-flutter-project-v1.appspot.com',
//     iosClientId: '882228347283-eg3307vb2ntvpci3si2p8tteao87q3a9.apps.googleusercontent.com',
//     iosBundleId: 'com.example.flutterLab',
//   );
// }
